# Generated by Django 3.1.2 on 2020-11-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='post',
            name='timecode',
            field=models.CharField(editable=False, max_length=14, null=True),
        ),
    ]
